[server]
bind_addr = "127.0.0.1:8080"

[cache]
storage_path = "./cache"
default_ttl = 3600  # 秒

[upstream]
# 可选：上游代理配置
proxy_url = "http://172.16.0.80:9051"

[user_agent]
# 模拟User-Agent
value = "Mozilla/5.0 ( compatible crates-proxy/0.1.0 )"

[logging]
level = "info"