[server]
bind_addr = "127.0.0.1:8080"

[cache]
storage_path = "./cache"
default_ttl = 3600  # 秒

[upstream]
# 可选：上游代理配置
# proxy_url = "http://proxy.example.com:8080"
# 或
# proxy_url = "socks5://proxy.example.com:1080"

[user_agent]
# 模拟User-Agent
value = "Mozilla/5.0 ( compatible crates-proxy/0.1.0 )"

[logging]
level = "info"